# Generated by Django 2.2.4 on 2019-09-28 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtable', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='fileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=30)),
                ('file_path', models.FileField(upload_to='./upload/')),
            ],
        ),
    ]
